# -*- coding: utf-8 -*-
"""DistilBERT_finetuned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJJPd9RUco1mQ107YkJduqPm5Iup-5st
"""

from google.colab import drive
drive.mount("/content/drive")

!pip install -q "transformers==4.35.2" "accelerate==0.26.1" "peft==0.7.1" --upgrade

!pip install -q transformers==4.35.2 accelerate==0.26.1 peft==0.7.1 --upgrade

# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

**Libraries**
"""
#Libraries
import numpy as np
import pandas as pd
import re

# Visualization tools
import matplotlib.pyplot as plt
import seaborn as sns

# Word Cloud library
from wordcloud import WordCloud, STOPWORDS

# Library used for data preprocessing
from datasets import load_dataset, DatasetDict, Dataset, ClassLabel
from transformers import AutoTokenizer

# Model selection libraries
from sklearn.model_selection import train_test_split

# Library used for ignore warnings
import warnings
warnings.filterwarnings('ignore')

import os

base_dir = os.getcwd()
data_dir = os.path.join(base_dir, "data")
models_dir = os.path.join(base_dir, "models")

os.makedirs(data_dir, exist_ok=True)
os.makedirs(models_dir, exist_ok=True)

"""**Dataset Loading**"""

dataset = load_dataset("bourigue/data_email_spam")
print(dataset)

df = dataset['train'].to_pandas()
df.head()

print(f"Dataset loaded: {len(df)} samples")
print(f"Class distribution:\n{df['label'].value_counts()}\n")

"""**Dataset Visualization**"""

import matplotlib.pyplot as plt

# Label distribution
spread = df['label'].value_counts()

# Pie chart
plt.rcParams['figure.figsize'] = (5, 5)
spread.plot(kind='pie', autopct='%1.2f%%', cmap='Set1')
plt.title('Distribution of Spam vs Ham')
plt.ylabel('')
plt.show()

"""Word Cloud Visualization:"""

df_spam = df[df['label'] == 1]
stopwords = set(STOPWORDS)
text = " ".join(df_spam['text_combined'].astype(str).tolist()).lower()

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color='white',
    stopwords=stopwords,
    max_words=1000
).generate(text)

plt.figure(figsize=(6, 6))
plt.title("Most Used Words in Spam Messages", fontsize=15, pad=20)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

"""**Preprocessing Dataset**"""

CONFIG = {
    'model_name': 'distilbert-base-uncased',
    'max_length': 128,
    'train_split': 0.7,
    'val_split': 0.1,
    'test_split': 0.2,
    'seed': 42
}

# Normalization:

def normalize_text(text):
    #Normalizing and cleaning email text while preserving spam indicators

    if pd.isna(text):
        return ""

    text = str(text)

    #Lowercase
    text = text.lower()

    #Normalize repeated characters (such as "oooo " or "eeeee")
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)

    #Normalize numbers and replace with NUMBER token
    text = re.sub(r'\d+', ' NUMBER ', text)

    #Normalize currency symbols
    text = re.sub(r'[$£€¥₹]', ' CURRENCY ', text)

    #Replace URLs with URL token
    text = re.sub(r'http\S+|www\.\S+', ' URL ', text)

    #Replace email addresses with EMAIL token
    text = re.sub(r'\S+@\S+', ' EMAIL ', text)

    #Normalize excessive punctuation
    text = re.sub(r'!{2,}', ' EXCLAMATION ', text)
    text = re.sub(r'\?{2,}', ' QUESTION ', text)

    #Remove HTML tags
    text = re.sub(r'<[^>]+>', '', text)

    #Remove special characters
    text = re.sub(r'[^\w\s!?$]', ' ', text)

    #Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    #Remove very short texts
    if len(text) < 10:
        return ""

    return text

df['text_combined'] = df['text_combined'].apply(normalize_text)

# Remove empty texts after normalization
df = df[df['text_combined'].str.len() > 0].reset_index(drop=True)
print(f"Normalization complete: {len(df)} samples remaining")

## save the cleaned dataset (for TF-IDF models) !!! put in gitignore
cleaned_path = os.path.join(data_dir, "cleaned_spam_dataset.csv")
df.to_csv(cleaned_path, index=False)

"""**Splitting dataset**"""

#Test set:
train_val_df, test_df = train_test_split(
    df,
    test_size=CONFIG['test_split'],
    random_state=CONFIG['seed'],
    stratify=df['label']
)

#Validation set from training set:
val_size = CONFIG['val_split'] / (CONFIG['train_split'] + CONFIG['val_split'])
train_df, val_df = train_test_split(
    train_val_df,
    test_size=val_size,
    random_state=CONFIG['seed'],
    stratify=train_val_df['label']
)

print(f" Train set: {len(train_df)} samples")
print(f"  - Ham: {(train_df['label']==0).sum()}, Spam: {(train_df['label']==1).sum()}")
print(f" Validation set: {len(val_df)} samples")
print(f"  - Ham: {(val_df['label']==0).sum()}, Spam: {(val_df['label']==1).sum()}")
print(f" Test set: {len(test_df)} samples")
print(f"  - Ham: {(test_df['label']==0).sum()}, Spam: {(test_df['label']==1).sum()}")

## save individual splits for consistency
train_path = os.path.join(data_dir, "train_split.csv")
val_path   = os.path.join(data_dir, "val_split.csv")
test_path  = os.path.join(data_dir, "test_split.csv")

train_df.to_csv(train_path, index=False)
val_df.to_csv(val_path, index=False)
test_df.to_csv(test_path, index=False)

"""**Tokenization**"""

def tokenize_function(examples):

    tokens = tokenizer(
        examples['text_combined'],
        max_length=CONFIG['max_length'],
        padding='max_length',
        truncation=True,
        return_attention_mask=True
    )
    tokens['labels'] = examples['label']
    return tokens

tokenizer = AutoTokenizer.from_pretrained(CONFIG['model_name'])

train_dataset = Dataset.from_pandas(train_df[['text_combined', 'label']])
val_dataset = Dataset.from_pandas(val_df[['text_combined', 'label']])
test_dataset = Dataset.from_pandas(test_df[['text_combined', 'label']])

tokenized_train = train_dataset.map(tokenize_function, batched=True, remove_columns=['text_combined', 'label'])
tokenized_val = val_dataset.map(tokenize_function, batched=True, remove_columns=['text_combined', 'label'])
tokenized_test = test_dataset.map(tokenize_function, batched=True, remove_columns=['text_combined', 'label'])

#Final Dataset:
final_dataset = DatasetDict({'train': tokenized_train, 'validation': tokenized_val,'test': tokenized_test})

print(final_dataset)

## Save the tokenized dataset (for transformers)
tokenized_path = "/content/drive/MyDrive/distilbert_spam_optuna"
final_dataset.save_to_disk(tokenized_path)
print("Saved to Drive:", tokenized_path)

!pip install optuna
!pip install optuna-integration

import os
os.environ["TRANSFORMERS_NO_TF"] = "1"

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
    set_seed,
)
from transformers.trainer_callback import TrainerCallback
from datasets import load_from_disk

import optuna
from optuna.visualization import plot_optimization_history, plot_param_importances

import warnings
warnings.filterwarnings("ignore")

try:
    BASE_DIR = "/content/drive/MyDrive/distilbert_spam_optuna"
    print("Using Google Drive base dir:", BASE_DIR)
except ImportError:
    BASE_DIR = os.getcwd()

DATA_DIR = BASE_DIR

MODEL_DIR  = os.path.join(BASE_DIR, "models", "final_distilbert_spam_classifier")
LOG_DIR    = os.path.join(BASE_DIR, "logs")
PLOT_DIR   = os.path.join(BASE_DIR, "plots")
OPTUNA_DIR = os.path.join(PLOT_DIR, "optuna")
OPTUNA_DB  = os.path.join(BASE_DIR, "optuna_distilbert_spam.db")

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(PLOT_DIR, exist_ok=True)
os.makedirs(OPTUNA_DIR, exist_ok=True)
os.makedirs(os.path.dirname(DATA_DIR), exist_ok=True)

# incremental CSV to log each trial as soon as it's done
TRIALS_CSV = os.path.join(OPTUNA_DIR, "optuna_trials_incremental.csv")

# total trials (overall)
N_TARGET_TRIALS = 8

set_seed(42)

class MetricsCallback(TrainerCallback):
    def __init__(self):
        self.train_steps, self.train_losses = [], []
        self.eval_steps,  self.eval_losses  = [], []
        self.metric_steps = []
        self.eval_accuracy = []
        self.eval_f1 = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if not logs:
            return
        if "loss" in logs:
            self.train_steps.append(state.global_step)
            self.train_losses.append(logs["loss"])

        if "eval_loss" in logs:
            self.eval_steps.append(state.global_step)
            self.eval_losses.append(logs["eval_loss"])

        if "eval_accuracy" in logs:
            self.metric_steps.append(state.global_step)
            self.eval_accuracy.append(logs["eval_accuracy"])

        if "eval_f1" in logs:
            self.eval_f1.append(logs["eval_f1"])

# ------------------------------------------------------------
# 3) Load dataset & tokenizer
# ------------------------------------------------------------
print("Loading dataset from:", DATA_DIR)
dataset = load_from_disk(DATA_DIR)
dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

train_ds = dataset["train"]
val_ds   = dataset["validation"]
test_ds  = dataset["test"]

print("Loading tokenizer...")
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

!ls -R "/content/drive/MyDrive/distilbert_spam_optuna"

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="binary")
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "precision": precision, "recall": recall, "f1": f1}

def log_trial_result(trial, eval_result, lr, wd, epochs, bsz, drop):
    row = {
        "trial_number": trial.number,
        "learning_rate": lr,
        "weight_decay": wd,
        "num_train_epochs": epochs,
        "per_device_train_batch_size": bsz,
        "dropout": drop,
        "eval_loss": float(eval_result["eval_loss"]),
        "eval_accuracy": float(eval_result["eval_accuracy"]),
        "eval_precision": float(eval_result["eval_precision"]),
        "eval_recall": float(eval_result["eval_recall"]),
        "eval_f1": float(eval_result["eval_f1"]),
    }

    df = pd.DataFrame([row])
    file_exists = os.path.exists(TRIALS_CSV)

    df.to_csv(
        TRIALS_CSV,
        mode="a" if file_exists else "w",
        header=not file_exists,
        index=False,
    )

def objective(trial: optuna.Trial) -> float:
    lr     = trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True)
    wd     = trial.suggest_float("weight_decay", 0.0, 0.1)
    epochs = trial.suggest_int("num_train_epochs", 2, 3)
    bsz    = trial.suggest_categorical("per_device_train_batch_size", [16, 32])
    drop   = trial.suggest_float("dropout", 0.1, 0.4)

    model = DistilBertForSequenceClassification.from_pretrained(
        "distilbert-base-uncased",
        num_labels=2,
    )

    # DistilBERT dropout config fields
    model.config.dropout = drop
    model.config.attention_dropout = drop

    out_dir = os.path.join(MODEL_DIR, "optuna_tmp", f"trial_{trial.number}")
    os.makedirs(out_dir, exist_ok=True)

    args = TrainingArguments(
        output_dir=out_dir,
        overwrite_output_dir=True,
        num_train_epochs=epochs,
        per_device_train_batch_size=bsz,
        per_device_eval_batch_size=64,
        learning_rate=lr,
        weight_decay=wd,
        evaluation_strategy="epoch",
        logging_strategy="no",
        save_strategy="no",
        fp16=torch.cuda.is_available(),
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    eval_result = trainer.evaluate()

    trainer.save_model(out_dir)

    trial.set_user_attr("eval_loss", float(eval_result["eval_loss"]))
    trial.set_user_attr("eval_accuracy", float(eval_result["eval_accuracy"]))
    trial.set_user_attr("eval_precision", float(eval_result["eval_precision"]))
    trial.set_user_attr("eval_recall", float(eval_result["eval_recall"]))
    trial.set_user_attr("eval_f1", float(eval_result["eval_f1"]))

    log_trial_result(trial, eval_result, lr, wd, epochs, bsz, drop)

    return eval_result["eval_f1"]

print("\n=== Optuna hyperparameter search ===")

storage_url = f"sqlite:///{OPTUNA_DB}"
print("Optuna storage:", storage_url)

study = optuna.create_study(
    direction="maximize",
    study_name="distilbert_spam_optuna",
    storage=storage_url,
    load_if_exists=True,
)

n_existing = len(study.trials)
print(f"Existing trials in DB: {n_existing}")

n_to_run = max(0, N_TARGET_TRIALS - n_existing)
print(f"Target total trials: {N_TARGET_TRIALS} -> running {n_to_run} new trials")

if n_to_run > 0:
    study.optimize(objective, n_trials=n_to_run, show_progress_bar=True)
else:
    print("No new trials needed; already reached target number of trials.")

print("Best F1:", study.best_trial.value)
print("Best params:", study.best_trial.params)

study_df = study.trials_dataframe()
study_df.to_csv(os.path.join(OPTUNA_DIR, "optuna_trials_full_snapshot.csv"), index=False)

class MetricsTracker(TrainerCallback):
    def __init__(self):
        self.train_steps = []
        self.train_loss = []
        self.eval_steps = []
        self.eval_loss = []
        self.eval_accuracy = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs and "loss" in logs:
            self.train_steps.append(state.global_step)
            self.train_loss.append(logs["loss"])

    def on_evaluate(self, args, state, control, metrics=None, **kwargs):
        if metrics:
            self.eval_steps.append(state.global_step)
            self.eval_loss.append(metrics.get("eval_loss"))
            self.eval_accuracy.append(metrics.get("eval_accuracy"))


tracker = MetricsTracker()

best_params = study.best_trial.params
print("Using best params:", best_params)

from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2,
)

# Apply best dropout from Optuna
model.config.dropout = best_params["dropout"]
model.config.attention_dropout = best_params["dropout"]

best_training_args = TrainingArguments(
    output_dir=BEST_MODEL_DIR,
    overwrite_output_dir=True,

    num_train_epochs=best_params["num_train_epochs"],
    per_device_train_batch_size=best_params["per_device_train_batch_size"],

    per_device_eval_batch_size=64,
    learning_rate=best_params["learning_rate"],
    weight_decay=best_params["weight_decay"],

    logging_steps=100,
    eval_steps=200,
    evaluation_strategy="steps",
    save_strategy="epoch",
    fp16=torch.cuda.is_available(),
    report_to="none",
)

best_trainer = Trainer(
    model=model,
    args=best_training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[tracker],
)

best_trainer.train()

# Save final best model
best_trainer.save_model(BEST_MODEL_DIR)
tokenizer.save_pretrained(BEST_MODEL_DIR)

# Evaluate on test set
test_metrics = best_trainer.evaluate(test_ds)
print("Test metrics:", test_metrics)

fig, ax1 = plt.subplots(figsize=(10, 5))

# Loss curves
ax1.plot(tracker.train_steps, tracker.train_loss, label="Training Loss")
ax1.plot(tracker.eval_steps, tracker.eval_loss, label="Validation Loss")
ax1.set_xlabel("Training Steps")
ax1.set_ylabel("Loss")
ax1.grid(True, linestyle="--", alpha=0.4)
ax1.legend(loc="upper left")

# Validation accuracy curve (second y-axis)
ax2 = ax1.twinx()
ax2.plot(
    tracker.eval_steps,
    tracker.eval_accuracy,
    label="Validation Accuracy",
    marker="o",
    linestyle="--",
)
ax2.set_ylabel("Accuracy")

plt.title("DistilBERT – Training Loss, Validation Loss & Validation Accuracy")
plt.tight_layout()

# Save plot to Drive
plot_path = os.path.join(PLOTS_DIR, "distilbert_training_curves.png")
plt.savefig(plot_path, dpi=150)
plt.show()

print("Saved training curve plot to:", plot_path)

from optuna.visualization import (
    plot_optimization_history,
    plot_param_importances
)

print("Saving Optuna plots as HTML...")

hist_fig = plot_optimization_history(study)
hist_fig.update_layout(title="Optuna Optimization History (DistilBERT)")
hist_html = os.path.join(OPTUNA_DIR, "distilbert_optuna_history.html")
hist_fig.write_html(hist_html)
print("Saved:", hist_html)

imp_fig = plot_param_importances(study)
imp_fig.update_layout(title="Optuna Parameter Importances (DistilBERT)")
imp_html = os.path.join(OPTUNA_DIR, "distilbert_optuna_importances.html")
imp_fig.write_html(imp_html)
print("Saved:", imp_html)

# ---- Test Evaluation ----
print("Evaluating on test set...")
test_results = best_trainer.evaluate(test_ds)

for k, v in test_results.items():
    if isinstance(v, float):
        print(f"{k}: {v:.4f}")

# Save final model & tokenizer
best_trainer.save_model(BEST_MODEL_DIR)
tokenizer.save_pretrained(BEST_MODEL_DIR)

# Save test metrics
pd.DataFrame([test_results]).to_csv(
    os.path.join(BEST_MODEL_DIR, "distilbert_test_results.csv"),
    index=False,
)

train_loss_df = pd.DataFrame({
    "step": tracker.train_steps,
    "loss": tracker.train_loss
})

eval_loss_df = pd.DataFrame({
    "step": tracker.eval_steps,
    "loss": tracker.eval_loss
})

eval_acc_df = pd.DataFrame({
    "step": tracker.eval_steps,
    "eval_accuracy": tracker.eval_accuracy
})

# Save CSV files
train_loss_df.to_csv(os.path.join(BEST_MODEL_DIR, "train_loss_history.csv"), index=False)
eval_loss_df.to_csv(os.path.join(BEST_MODEL_DIR, "eval_loss_history.csv"), index=False)
eval_acc_df.to_csv(os.path.join(BEST_MODEL_DIR, "eval_accuracy_history.csv"), index=False)

print("\nSaved training curves & test metrics in:", BEST_MODEL_DIR)

plt.figure(figsize=(10, 5))

# Train loss
plt.plot(tracker.train_steps, tracker.train_loss,
         label="Train Loss", color="blue")

# Validation loss
plt.plot(tracker.eval_steps, tracker.eval_loss,
         label="Validation Loss", color="orange", marker="o")

plt.xlabel("Training steps")
plt.ylabel("Loss")
plt.title("DistilBERT (Best Hyperparams) – Train vs Validation Loss")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()

loss_plot_path = os.path.join(PLOT_DIR, "distilbert_loss_curve_best.png")
plt.savefig(loss_plot_path, dpi=300)
plt.close()

print("Saved loss curve:", loss_plot_path)

plt.figure(figsize=(10, 5))

plt.plot(tracker.eval_steps, tracker.eval_accuracy,
         label="Validation Accuracy", marker="o", color="green")

plt.xlabel("Training steps")
plt.ylabel("Accuracy")
plt.title("DistilBERT – Validation Accuracy Curve (Best Hyperparams)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()

metric_plot_path = os.path.join(PLOT_DIR, "distilbert_accuracy_curve_best.png")
plt.savefig(metric_plot_path, dpi=300)
plt.close()

print("Saved accuracy curve:", metric_plot_path)

import optuna.visualization as viz

viz.plot_optimization_history(study).show()
viz.plot_parallel_coordinate(study).show()
viz.plot_param_importances(study).show()
viz.plot_contour(study).show()

import optuna.visualization as viz
import os

os.makedirs(OPTUNA_DIR, exist_ok=True)

print("Saving Optuna HTML plots...")

# --- Optimization History ---
hist_fig = viz.plot_optimization_history(study)
hist_path = os.path.join(OPTUNA_DIR, "distilbert_optuna_history.html")
hist_fig.write_html(hist_path)
print("Saved:", hist_path)

# --- Parallel Coordinate ---
parallel_fig = viz.plot_parallel_coordinate(study)
parallel_path = os.path.join(OPTUNA_DIR, "distilbert_optuna_parallel.html")
parallel_fig.write_html(parallel_path)
print("Saved:", parallel_path)

# --- Parameter Importances ---
import_fig = viz.plot_param_importances(study)
import_path = os.path.join(OPTUNA_DIR, "distilbert_optuna_importances.html")
import_fig.write_html(import_path)
print("Saved:", import_path)

# --- Contour Plot ---
contour_fig = viz.plot_contour(study)
contour_path = os.path.join(OPTUNA_DIR, "distilbert_optuna_contour.html")
contour_fig.write_html(contour_path)
print("Saved:", contour_path)

print("\nAll Optuna plots saved as HTML.")

plt.figure(figsize=(12, 6))

# -------------------------------
# Left axis: Loss curves
# -------------------------------
ax1 = plt.gca()   # main axis

# Train loss
ax1.plot(tracker.train_steps, tracker.train_loss,
         label="Train Loss", color="blue", linewidth=2)

# Validation loss
ax1.plot(tracker.eval_steps, tracker.eval_loss,
         label="Validation Loss", color="orange", marker="o", linewidth=2)

ax1.set_xlabel("Training Steps")
ax1.set_ylabel("Loss", color="blue")
ax1.tick_params(axis='y', labelcolor="blue")
ax1.grid(True, alpha=0.3)

# -------------------------------
# Right axis: Accuracy curve
# -------------------------------
ax2 = ax1.twinx()

ax2.plot(tracker.eval_steps, tracker.eval_accuracy,
         label="Validation Accuracy", color="green", marker="s", linewidth=2)

ax2.set_ylabel("Accuracy", color="green")
ax2.tick_params(axis='y', labelcolor="green")

# -------------------------------
# Title & Legends
# -------------------------------
plt.title("DistilBERT – Training Loss, Validation Loss, and Validation Accuracy")

# Combined legend
lines_1, labels_1 = ax1.get_legend_handles_labels()
lines_2, labels_2 = ax2.get_legend_handles_labels()

plt.legend(lines_1 + lines_2, labels_1 + labels_2, loc="upper right")

plt.tight_layout()

combined_plot_path = os.path.join(PLOT_DIR, "distilbert_loss_accuracy_combined.png")
plt.savefig(combined_plot_path, dpi=300)
plt.close()

print("Saved combined curve:", combined_plot_path)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# ---------------------------
# Get predictions from model
# ---------------------------
pred_output = best_trainer.predict(test_ds)
logits = pred_output.predictions
labels = pred_output.label_ids

preds = np.argmax(logits, axis=-1)

# ---------------------------
# Build confusion matrix
# ---------------------------
cm = confusion_matrix(labels, preds)

# Optional: class names (0 = ham, 1 = spam or whatever your dataset uses)
class_names = ["Ham", "Spam"]

# ---------------------------
# Plot confusion matrix
# ---------------------------
plt.figure(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap="Blues", values_format='d')

plt.title("DistilBERT Confusion Matrix (DistilBERT)")
plt.grid(False)

# Save PNG
cm_path = os.path.join(PLOT_DIR, "distilbert_confusion_matrix.png")
plt.savefig(cm_path, dpi=300, bbox_inches="tight")
plt.close()

print("Saved confusion matrix:", cm_path)

plt.figure(figsize=(12, 6))

ax1 = plt.gca()

# Train Loss
ax1.plot(tracker.train_steps, tracker.train_loss,
         label="Train Loss", color="blue", linewidth=2)

# Validation Loss
ax1.plot(tracker.eval_steps, tracker.eval_loss,
         label="Validation Loss", color="orange", marker="o", linewidth=2)

ax1.set_xlabel("Training Steps")
ax1.set_ylabel("Loss", color="blue")
ax1.tick_params(axis='y', labelcolor="blue")
ax1.grid(True, alpha=0.3)

# Accuracy on 2nd axis
ax2 = ax1.twinx()
ax2.plot(tracker.eval_steps, tracker.eval_accuracy,
         label="Validation Accuracy", color="green", marker="s", linewidth=2)
ax2.set_ylabel("Accuracy", color="green")
ax2.tick_params(axis='y', labelcolor="green")

# Title
plt.title("DistilBERT – Training Loss, Validation Loss, and Validation Accuracy")

lines_1, labels_1 = ax1.get_legend_handles_labels()
lines_2, labels_2 = ax2.get_legend_handles_labels()

plt.legend(lines_1 + lines_2, labels_1 + labels_2,
           loc="upper left", bbox_to_anchor=(0.80, 0.55))

plt.tight_layout()

combined_plot_path = os.path.join(PLOT_DIR, "distilbert_update_combined.png")
plt.savefig(combined_plot_path, dpi=300, bbox_inches="tight")
plt.close()

print("Saved combined curve:", combined_plot_path)

import optuna.visualization as viz
import os

os.makedirs(OPTUNA_DIR, exist_ok=True)

print("Saving Optuna HTML plots...")

def resize_and_save(fig, filename, width=1200, height=900):
    """
    Resize plotly Optuna figure and save as HTML.
    """
    fig.update_layout(
        autosize=False,
        width=width,
        height=height
    )
    html_path = os.path.join(OPTUNA_DIR, filename + ".html")
    fig.write_html(html_path)
    print("Saved:", html_path)


# --- Optimization History ---
hist_fig = viz.plot_optimization_history(study)
resize_and_save(hist_fig, "distilbert_optuna_history")

# --- Parallel Coordinate ---
parallel_fig = viz.plot_parallel_coordinate(study)
resize_and_save(parallel_fig, "distilbert_optuna_parallel")

# --- Parameter Importances ---
import_fig = viz.plot_param_importances(study)
resize_and_save(import_fig, "distilbert_optuna_importances")

# --- Contour Plot ---
contour_fig = viz.plot_contour(study)
resize_and_save(contour_fig, "distilbert_optuna_contour")

print("\nAll Optuna plots saved as HTML.")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Predictions
y_true = test_ds["labels"]
y_pred = best_trainer.predict(test_ds).predictions.argmax(axis=1)

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)

# ---- Plot ----
plt.figure(figsize=(10, 10))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    cbar=True,
    square=True,
    linewidths=0.5,
    annot_kws={"size": 18}
)

plt.title("Confusion Matrix - DistilBERT", fontsize=22, pad=20)

# Axis labels
plt.ylabel("Actual Label", fontsize=18)
plt.xlabel("Predicted Label", fontsize=18)

# Tick label sizes
plt.xticks(fontsize=16)
plt.yticks(fontsize=16, rotation=0)

# Save
cm_path = os.path.join(PLOT_DIR, "distilbert_confusion_matrix_update.png")
plt.savefig(cm_path, dpi=300, bbox_inches="tight")
plt.close()

print("Saved confusion matrix:", cm_path)